server:
  servlet:
    context-path: /serverChat
spring:
  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
#    driverClassName: com.mysql.jdbc.Driver
    driverClassName: org.postgresql.Driver
#    url: jdbc:mysql://localhost:3306/chatserver
    url: jdbc:postgresql://localhost:5432/chatserver
    username: julian
    password: gbdrdflhfnt